# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_feedback', models.TextField()),
                ('your_email', models.EmailField(blank=True, max_length=254)),
                ('your_file', models.FileField(blank=True, upload_to='')),
                ('date', models.DateTimeField()),
                ('your_subject', models.CharField(max_length=25)),
            ],
        ),
    ]
