# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitfeedback',
            name='has_been_read',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
