# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_submitfeedback_has_been_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfeedback',
            name='has_been_read',
            field=models.BooleanField(default=False),
        ),
    ]
